vis:
  appId: "wgtSdkTest"
  service:
    sinoiv:
      url: "http://sinoiv.jd.com"
    gvr:
      url: "http://sinoiv.jd.com"
grpc:
  server:
      port: 9090
      address: 0.0.0.0
  client:
      GLOBAL:
         negotiationType: plaintext
      local-grpc-server:
         address: 'static://127.0.0.1:9090'
dc:
    host: 52.82.4.65
wgtGrpc:
      wgtId: "110"

